# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: test
    name: test
    stages: [commit]
    language: system
    entry: bash ./scripts/test.sh
    types: [python]
    pass_filenames: false
