name: New contributor message

on:
  pull_request_target:
    types: [opened]

jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Hello! Thank you for your contribution 💪

            As it's your first contribution be sure to check out the [contribution notes](https://reforms.boardpack.org/contributing/).

            Welcome aboard ⛵️!
